module sram #(
    parameter WIDTH = 8,
    parameter DEPTH = 256
) (
    input logic clk,
    input logic enable_a_n,
    input logic enable_b_n,
    input logic write_enable_a_n,
    input logic write_enable_b_n,
    input logic [WIDTH-1:0] data_a,
    input logic [WIDTH-1:0] data_b,
    input logic [$clog2(DEPTH)-1:0] address_a,
    input logic [$clog2(DEPTH)-1:0] address_b,
    output logic [WIDTH-1:0] q_a,
    output logic [WIDTH-1:0] q_b
);

if (WIDTH == 256 && DEPTH == 64) begin : sram_256x64
  IN22FDX_SDPV_NFVG_W00064B064M04C064 sram_macro_0 (
    .CLK_A(clk),
    .CLK_B(clk),
    .CEN_A(enable_a_n),
    .CEN_B(enable_b_n),
    .RDWEN_A(write_enable_a_n),
    .RDWEN_B(write_enable_b_n),
    .DEEPSLEEP(1'b0),
    .POWERGATE(1'b0),
    .AS_A(address_a[$clog2(DEPTH)-1]),
    .AW_A(address_a[$clog2(DEPTH)-2:2]),
    .AC_A(address_a[1:0]),
    .AS_B(address_b[$clog2(DEPTH)-1]),
    .AW_B(address_b[$clog2(DEPTH)-2:2]),
    .AC_B(address_b[1:0]),
    .D_A(data_a[63:0]),
    .BW_A({64{1'b1}}),
    .D_B(data_b[63:0]),
    .BW_B({64{1'b1}}),
    .T_BIST(1'b0),
    .T_LOGIC(1'b0),
    .T_CEN_A(1'b0),
    .T_CEN_B(1'b0),
    .T_RDWEN_A(1'b0),
    .T_RDWEN_B(1'b0),
    .T_DEEPSLEEP(1'b0),
    .T_POWERGATE(1'b0),
    .T_AS_A(1'b0),
    .T_AW_A({3{1'b0}}),
    .T_AC_A({2{1'b0}}),
    .T_AS_B(1'b0),
    .T_AW_B({3{1'b0}}),
    .T_AC_B({2{1'b0}}),
    .T_D_A({64{1'b0}}),
    .T_BW_A({64{1'b0}}),
    .T_D_B({64{1'b0}}),
    .T_BW_B({64{1'b0}}),
    .T_WBT(1'b0),
    .T_STAB(1'b0),
    .MA_SAWL({2{1'b0}}),
    .MA_WL({2{1'b0}}),
    .MA_WRAS({2{1'b0}}),
    .MA_WRASD(1'b0),
    .Q_A(q_a[63:0]),
    .Q_B(q_b[63:0]),
    .OBSV_CTL_A(),
    .OBSV_CTL_B()
  );

  IN22FDX_SDPV_NFVG_W00064B064M04C064 sram_macro_1 (
    .CLK_A(clk),
    .CLK_B(clk),
    .CEN_A(enable_a_n),
    .CEN_B(enable_b_n),
    .RDWEN_A(write_enable_a_n),
    .RDWEN_B(write_enable_b_n),
    .DEEPSLEEP(1'b0),
    .POWERGATE(1'b0),
    .AS_A(address_a[$clog2(DEPTH)-1]),
    .AW_A(address_a[$clog2(DEPTH)-2:2]),
    .AC_A(address_a[1:0]),
    .AS_B(address_b[$clog2(DEPTH)-1]),
    .AW_B(address_b[$clog2(DEPTH)-2:2]),
    .AC_B(address_b[1:0]),
    .D_A(data_a[127:64]),
    .BW_A({64{1'b1}}),
    .D_B(data_b[127:64]),
    .BW_B({64{1'b1}}),
    .T_BIST(1'b0),
    .T_LOGIC(1'b0),
    .T_CEN_A(1'b0),
    .T_CEN_B(1'b0),
    .T_RDWEN_A(1'b0),
    .T_RDWEN_B(1'b0),
    .T_DEEPSLEEP(1'b0),
    .T_POWERGATE(1'b0),
    .T_AS_A(1'b0),
    .T_AW_A({3{1'b0}}),
    .T_AC_A({2{1'b0}}),
    .T_AS_B(1'b0),
    .T_AW_B({3{1'b0}}),
    .T_AC_B({2{1'b0}}),
    .T_D_A({64{1'b0}}),
    .T_BW_A({64{1'b0}}),
    .T_D_B({64{1'b0}}),
    .T_BW_B({64{1'b0}}),
    .T_WBT(1'b0),
    .T_STAB(1'b0),
    .MA_SAWL({2{1'b0}}),
    .MA_WL({2{1'b0}}),
    .MA_WRAS({2{1'b0}}),
    .MA_WRASD(1'b0),
    .Q_A(q_a[127:64]),
    .Q_B(q_b[127:64]),
    .OBSV_CTL_A(),
    .OBSV_CTL_B()
  );

  IN22FDX_SDPV_NFVG_W00064B064M04C064 sram_macro_2 (
    .CLK_A(clk),
    .CLK_B(clk),
    .CEN_A(enable_a_n),
    .CEN_B(enable_b_n),
    .RDWEN_A(write_enable_a_n),
    .RDWEN_B(write_enable_b_n),
    .DEEPSLEEP(1'b0),
    .POWERGATE(1'b0),
    .AS_A(address_a[$clog2(DEPTH)-1]),
    .AW_A(address_a[$clog2(DEPTH)-2:2]),
    .AC_A(address_a[1:0]),
    .AS_B(address_b[$clog2(DEPTH)-1]),
    .AW_B(address_b[$clog2(DEPTH)-2:2]),
    .AC_B(address_b[1:0]),
    .D_A(data_a[191:128]),
    .BW_A({64{1'b1}}),
    .D_B(data_b[191:128]),
    .BW_B({64{1'b1}}),
    .T_BIST(1'b0),
    .T_LOGIC(1'b0),
    .T_CEN_A(1'b0),
    .T_CEN_B(1'b0),
    .T_RDWEN_A(1'b0),
    .T_RDWEN_B(1'b0),
    .T_DEEPSLEEP(1'b0),
    .T_POWERGATE(1'b0),
    .T_AS_A(1'b0),
    .T_AW_A({3{1'b0}}),
    .T_AC_A({2{1'b0}}),
    .T_AS_B(1'b0),
    .T_AW_B({3{1'b0}}),
    .T_AC_B({2{1'b0}}),
    .T_D_A({64{1'b0}}),
    .T_BW_A({64{1'b0}}),
    .T_D_B({64{1'b0}}),
    .T_BW_B({64{1'b0}}),
    .T_WBT(1'b0),
    .T_STAB(1'b0),
    .MA_SAWL({2{1'b0}}),
    .MA_WL({2{1'b0}}),
    .MA_WRAS({2{1'b0}}),
    .MA_WRASD(1'b0),
    .Q_A(q_a[191:128]),
    .Q_B(q_b[191:128]),
    .OBSV_CTL_A(),
    .OBSV_CTL_B()
  );

  IN22FDX_SDPV_NFVG_W00064B064M04C064 sram_macro_3 (
    .CLK_A(clk),
    .CLK_B(clk),
    .CEN_A(enable_a_n),
    .CEN_B(enable_b_n),
    .RDWEN_A(write_enable_a_n),
    .RDWEN_B(write_enable_b_n),
    .DEEPSLEEP(1'b0),
    .POWERGATE(1'b0),
    .AS_A(address_a[$clog2(DEPTH)-1]),
    .AW_A(address_a[$clog2(DEPTH)-2:2]),
    .AC_A(address_a[1:0]),
    .AS_B(address_b[$clog2(DEPTH)-1]),
    .AW_B(address_b[$clog2(DEPTH)-2:2]),
    .AC_B(address_b[1:0]),
    .D_A(data_a[255:192]),
    .BW_A({64{1'b1}}),
    .D_B(data_b[255:192]),
    .BW_B({64{1'b1}}),
    .T_BIST(1'b0),
    .T_LOGIC(1'b0),
    .T_CEN_A(1'b0),
    .T_CEN_B(1'b0),
    .T_RDWEN_A(1'b0),
    .T_RDWEN_B(1'b0),
    .T_DEEPSLEEP(1'b0),
    .T_POWERGATE(1'b0),
    .T_AS_A(1'b0),
    .T_AW_A({3{1'b0}}),
    .T_AC_A({2{1'b0}}),
    .T_AS_B(1'b0),
    .T_AW_B({3{1'b0}}),
    .T_AC_B({2{1'b0}}),
    .T_D_A({64{1'b0}}),
    .T_BW_A({64{1'b0}}),
    .T_D_B({64{1'b0}}),
    .T_BW_B({64{1'b0}}),
    .T_WBT(1'b0),
    .T_STAB(1'b0),
    .MA_SAWL({2{1'b0}}),
    .MA_WL({2{1'b0}}),
    .MA_WRAS({2{1'b0}}),
    .MA_WRASD(1'b0),
    .Q_A(q_a[255:192]),
    .Q_B(q_b[255:192]),
    .OBSV_CTL_A(),
    .OBSV_CTL_B()
  );

end else begin
    // Unsupported configuration
    $fatal("Unsupported configuration: WIDTH=%0d, DEPTH=%0d", WIDTH, DEPTH);
end

endmodule
