name: Build library

description: Builds DRRA library

inputs:
  use_sst:
    description: 'Enable USE_SST flag'
    required: false
    default: 'ON'
  sst-core-home:
    description: 'Path to SST Core installation'
    required: true
  sst-elements-home:
    description: 'Path to SST Elements installation'
    required: true

runs:
  using: composite
  steps:
    - name: Install dependencies
      run: sudo apt install libfuse2
      shell: bash
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Set environment variables
      shell: bash
      run: |
        echo "SST_CORE_HOME=${{ inputs.sst-core-home }}" >> $GITHUB_ENV
        echo "SST_ELEMENTS_HOME=${{ inputs.sst-elements-home }}" >> $GITHUB_ENV
        echo "SST_DIR=${{ inputs.sst-core-home }}/lib/cmake/SST" >> $GITHUB_ENV
        echo "PATH=${{ inputs.sst-core-home }}/bin:$PATH" >> $GITHUB_ENV

    - name: Check SST installation
      shell: bash
      run: |
        ls $SST_CORE_HOME/bin
        sst --version
        echo "SST installation found in cache"

    - name: Build library
      shell: bash
      run: |
        mkdir build
        cd build
        cmake -DUSE_SST=${{ inputs.use_sst }} ..
        cmake --build .
        echo "VESYLA_SUITE_PATH_COMPONENTS=$(pwd)/library" >> $GITHUB_ENV