name: Build testcases and library

on: push

jobs:
  build_testcases:
    uses: ./.github/workflows/assemble_testcases.yml
  download_testcases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: testcases
