name: Build library

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt install libfuse2
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Build library
      run: |
        mkdir build
        cd build
        cmake -DUSE_SST=ON ..
        make -j all
        echo "VESYLA_SUITE_PATH_COMPONENTS=$(pwd)/library" >> $GITHUB_ENV