name: Build testcases and library

on: 
  pull_request

jobs:
  build_testcases:
    uses: ./.github/workflows/assemble_testcases.yml
  # download_testcases:
  #   runs-on: ubuntu-latest
  #   needs: build_testcases
  #   steps:
  #     - uses: actions/download-artifact@v4
  #       with:
  #         name: testcases
