name: Create release

on:
  push:
    tags:
      - 'v*'

jobs:
  ci-build-sst:
    uses: ./.github/workflows/ci-build-sst.yml

  create_release:
    needs: ci-build-sst
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from tag
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - uses: actions/download-artifact@v4
        with:
          name: testcases

      - uses: actions/download-artifact@v4
        with:
          name: library

      - name: Release
        id: upload-release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          generate_release_notes: true
          files: |
            testcases.tar.gz
            library.tar.gz

