name: PR workflow

on:
  pull_request:

jobs:
  ci-sst-install:
    name: SST Install
    uses: ./.github/workflows/ci-sst-install.yml
    secrets: inherit

  ci-build-library-sst-off:
    name: Build DRRA Library without SST
    uses: ./.github/workflows/ci-build-library-sst-off.yml
    secrets: inherit

  ci-build-library:
    name: Build DRRA Library
    uses: ./.github/workflows/ci-build-library.yml
    needs: ci-sst-install
    secrets: inherit
    with:
      use_custom_ref: 'true'
      custom_ref: ${{ github.event.pull_request.head.sha }}

  ci-run-tests:
    name: Run DRRA Tests
    uses: ./.github/workflows/ci-run-tests.yml
    needs: ci-build-library
    secrets: inherit
    with:
      branch: ${{ needs.ci-build-library.outputs.branch }}
