name: Runs test

on:
  workflow_call:

jobs:
  run-tests:
    runs-on: [modelsim, vesyla, bender]
    steps:
      - name: Download library
        uses: actions/download-artifact@v4
        with:
          name: library
      - name: Extract library
        run: |
          tar -xzf library.tar.gz
          rm library.tar.gz
      - name: Checkout testcases
        uses: actions/checkout@v4
        with:
          repository: silagokth/drra-tests
          path: tests
          ref: master
          token: ${{ secrets.DRRA_TEST_PAT }}
      - name: Run tests
        run: |
          cd tests
          . /usr/share/modules/init/sh
          module use /opt/modules
          module avail
          module add questasim 
          module add vesyla
          module add bender
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          module add modelsim
          export VESYLA_SUITE_PATH_COMPONENTS=../library
          vesyla testcase generate -d ./testcases
          ./run.sh



