name: Run DRRA tests

on:
  workflow_call:
    inputs:
      branch:
        description: (optional) name of the drra-tests branch to run the tests on
        type: string
        default: 'master'

jobs:
  run-tests:
    runs-on: [modelsim, vesyla, bender, sst]
    steps:
      - name: Download vesyla
        uses: robinraju/release-downloader@v1
        with:
          out-file-path: bin
          fileName: vesyla
          repository: silagokth/vesyla
          latest: true

      - name: Download library
        uses: actions/download-artifact@v5
        with:
          name: library

      - name: Extract library
        run: |
          tar -xzf library.tar.gz
          rm library.tar.gz

      - name: Checkout testcases
        uses: actions/checkout@v4
        with:
          repository: silagokth/drra-tests
          path: tests
          ref: master
          token: ${{ secrets.DRRA_TEST_PAT }}

      - name: Check if a testing branch with the same name exists
        run: |
          cd "${{ github.workspace }}/tests"
          git fetch --all
          if git show-ref --verify --quiet refs/remotes/origin/${{ inputs.branch }}; then
            git checkout ${{ inputs.branch }}
            echo "Switching to drra-tests@${{ inputs.branch }}"
          else
            echo "Using the drra-tests master branch"
          fi

      - name: Run tests
        run: |
          cd "${{ github.workspace }}/tests"
          . /usr/share/modules/init/sh
          module use /opt/modules
          module add questasim 
          module add vesyla
          module add bender
          module add sst
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          export VESYLA_SUITE_PATH_COMPONENTS=$(readlink -e ../library)
          export GITHUB_PATH=${{ github.workspace }}/bin:$GITHUB_PATH
          export PATH=${{ github.workspace }}/bin:$PATH
          echo $GITHUB_PATH
          echo $PATH
          echo $(ls ${{ github.workspace }}/bin)
          vesyla --version
          ${{ github.workspace }}/bin/vesyla --version
          where vesyla
          which vesyla
          vesyla testcase generate -d ./testcases
          ./run.sh

      - name: Tar the tests outputs
        run: tar czf output.tar.gz tests/output

      - name: Upload test outputs
        uses: actions/upload-artifact@v4
        with:
          name: test-outputs
          path: output.tar.gz
