name: Install and cache SST

on:
  push:
    branches:
      - sst-workflow

env:
  SST_CORE_HOME: ${{ github.workspace }}/sstcore
  SST_ELEMENTS_HOME: ${{ github.workspace }}/sstelements

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: jwlawson/actions-setup-cmake@v2
    # - uses: actions/cache@v4
    #   env:
    #     cache-name: cache-sst
    #   with: 
    #     path: |
    #       ${{ github.workspace }}/build
    #       ${{ github.workspace }}/sstcore
    #       ${{ github.workspace }}/sstelements
    #     key: ${{ runner.os }}-build-${{ github.sha }}
    #     restore-keys: |
    #       ${{ runner.os }}-build-${{ github.sha }}
    #       ${{ runner.os }}-build-
    #       ${{ runner.os }}-
    # - if: ${{ steps.cache-sst.outputs.cache-hit != 'true' }}
    #   run: |
    #     echo "Cache not found, installing SST"
    # - name: Install dependencies
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y build-essential libltdl-dev  libtool libtool-bin autoconf automake
    # - name: Install SST Core
    #   if: ${{ steps.cache-sst.outputs.cache-hit != 'true' }}
    #   run: |
    #     wget https://github.com/sstsimulator/sst-core/releases/download/v14.1.0_Final/sstcore-14.1.0.tar.gz -O sstcore-14.1.0.tar.gz
    #     tar -xzf sstcore-14.1.0.tar.gz
    #     cd sst-core
    #     ./configure --prefix=$SST_CORE_HOME --disable-mpi && make -j4 && make install
    #     cd ..
    # - name: Add SST Core to PATH
    #   if: ${{ steps.cache-sst.outputs.cache-hit != 'true' }}
    #   run: |
    #     export PATH=$SST_CORE_HOME/bin:$PATH
    #     echo ${SST_CORE_HOME}/bin >> $GITHUB_PATH
    # - name: Install SST Elements
    #   if: ${{ steps.cache-sst.outputs.cache-hit != 'true' }}
    #   run: |
    #     wget https://github.com/sstsimulator/sst-elements/releases/download/v14.1.0_Final/sstelements-14.1.0.tar.gz -O sstelements-14.1.0.tar.gz
    #     tar -xzf sstelements-14.1.0.tar.gz
    #     cd sst-elements
    #     for folder in `ls -d ./src/sst/elements/*/`; do touch $folder/.ignore; done && rm -rf src/sst/elements/memHierarchy/.ignore
    #     ./autogen.sh
    #     ./configure --prefix=$SST_ELEMENTS_HOME && make -j4 && make install
    #     cd ..
    # - name: Add SST Elements to PATH
    #   if: ${{ steps.cache-sst.outputs.cache-hit != 'true' }}
    #   run: |
    #     export PATH=$SST_ELEMENTS_HOME/bin:$PATH
    #     echo ${SST_ELEMENTS_HOME}/bin >> $GITHUB_PATH
    # - name: Clean temp files
    #   if: ${{ steps.cache-sst.outputs.cache-hit != 'true' }}
    #   run: |
    #     rm -rf sstcore-14.1.0.tar.gz sst-core sstelements-14.1.0.tar.gz sst-elements
    - name: Build library
      uses: |
        actions/checkout@v4
        ./.github/workflows/build_library.yml
    - name: Build testcases
      uses: ./.github/workflows/build_testcases.yml