name: Rust

on:
  push:
    branches: [ "lib_refactor" ]
  pull_request:
    branches: [ "lib_refactor" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: echo $GITHUB_REF
    - uses: actions/checkout@v4
