name: Rust

on:
  push:
    branches: [ "lib_refactor" ]
  pull_request:
    branches: [ "lib_refactor" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: echo ${GITHUB_HEAD_REF:-$GITHUB_REF_NAME}
    - uses: actions/checkout@v4
